[tool.poetry]
name = "django4"
version = "0.1.0"
description = ""
authors = ["evgni3 <evgeniy.nikulin@sitronics-kt.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "4.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
